name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test
          # Python version to build the html sphinx documentation
          create-args: >-
            python=3.10 
          environment-file: .github/docs_env.yaml    # Path to the documentation conda environment
      - name: Installing the library
        shell: bash -l {0}
        run: |
          python setup.py install
      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: main
          dir_docs: docs_source
          sphinxapiopts: '-o ../ ../CRYSTALpytools/'
          sphinxapiexclude: '*setup* *.ipynb test*'
          sphinxopts: ''
      - name: Copy meta tag from Google Search Console
        shell: bash -l {0}
        run: |
          sed -i '/<head>/a\  <meta name="google-site-verification" content="VCwinqac8JtcGFEAmAYxTO3I1MmOx119sGsTHSDtFYE" />' docs_source/_build/html/index.html
